stages:
  preprocess_mnist:
    cmd: python src/preprocess.py
    deps:
    - src/preprocess.py
    outs:
    - data/data.pickle
    - data/mnist_data
  train_keras:
    cmd: python src/train_keras.py
    deps:
    - data/data.pickle
    - src/train_keras.py
    outs:
    - models/mnist_model_5.h5
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - models
    - src/evaluate.py
    outs:
    - reports/scores.json
  # train_forest:
  #   cmd: python src/train_forest.py
  #   deps:
  #   - data/data.pickle
  #   - src/train_forest.py
  #   outs:
  #   - models/random_forest_50.joblib
